services:

  Bundles\PasswordLoginBundle\Command\UserAdminCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
    tags:
      - { name: console.command }

  Bundles\PasswordLoginBundle\Command\UserVerifyCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
    tags:
      - { name: console.command }

  Bundles\PasswordLoginBundle\Command\UserTrustCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
    tags:
      - { name: console.command }

  Bundles\PasswordLoginBundle\Command\UserListCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
    tags:
      - { name: console.command }

  Bundles\PasswordLoginBundle\Command\UserPasswordCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
      - '@security.encoder_factory.generic'
    tags:
      - { name: console.command }

  Bundles\PasswordLoginBundle\Command\UserCronCommand:
    arguments:
      - '@Bundles\PasswordLoginBundle\Manager\CaptchaManager'
      - '@Bundles\PasswordLoginBundle\Manager\PasswordRecoveryManager'
      - '@Bundles\PasswordLoginBundle\Manager\EmailVerificationManager'
      - '@Bundles\PasswordLoginBundle\Manager\UserManager'
    tags:
      - { name: console.command }
