controllers:
    resource: ../../src/Controller/
    type: annotation

password_login:
    resource: ../../bundles/PasswordLoginBundle/Controller/
    type: annotation

sandbox:
    resource: ../../bundles/SandboxBundle/Controller/
    type: annotation
    prefix: /sandbox
    name_prefix: sandbox_