services:

  Bundles\ChartBundle\Bag\ContextTypeBag:

  Bundles\ChartBundle\ContextType\AbstractContextType:
    arguments:
      - '@form.factory'

  Bundles\ChartBundle\ContextType\StringContextType:
    parent: Bundles\ChartBundle\ContextType\AbstractContextType
    tags:
      - chart.context_type

#  Bundles\ChartBundle\ContextType\IntegerContextType:
#    parent: Bundles\ChartBundle\ContextType\AbstractContextType
#    tags:
#      - chart.context_type
#
#  Bundles\ChartBundle\ContextType\FloatContextType:
#    parent: Bundles\ChartBundle\ContextType\AbstractContextType
#    tags:
#      - chart.context_type
#
#  Bundles\ChartBundle\ContextType\AbsoluteDateContextType:
#    parent: Bundles\ChartBundle\ContextType\AbstractContextType
#    tags:
#      - chart.context_type
#
#  Bundles\ChartBundle\ContextType\RelativeDateContextType:
#    parent: Bundles\ChartBundle\ContextType\AbstractContextType
#    tags:
#      - chart.context_type
