services:

  Bundles\ChartBundle\Controller\HomeController:
    calls: [ [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ] ]
    tags:
      - controller.service_arguments
      - container.service_subscriber

  Bundles\ChartBundle\Controller\QueryController:
    arguments:
      - '@Bundles\ChartBundle\Manager\QueryManager'
    calls: [ [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ] ]
    tags:
      - controller.service_arguments
      - container.service_subscriber
