services:

  Bundles\ChartBundle\Context\Bag\FormatBag:

  Bundles\ChartBundle\Context\Format\AbstractContextFormat:
    arguments:
      - '@form.factory'

  Bundles\ChartBundle\Context\Format\StringFormat:
    parent: Bundles\ChartBundle\Context\Format\AbstractContextFormat
    tags:
      - chart.context_format
