services:

  Bundles\ApiBundle\Fetcher\EndpointListFetcher:
    arguments:
      - '@router'
      - '@controller_resolver'
      - '@doctrine.annotation_reader'

  Bundles\ApiBundle\Fetcher\StatusCodeFetcher:
    arguments:
      - '@doctrine.annotation_reader'

  doctrine.annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
