services:

  Bundles\ApiBundle\Fetcher\DocblockFetcher:

  Bundles\ApiBundle\Fetcher\EndpointCollectionFetcher:
    arguments:
      - '@router'
      - '@controller_resolver'
      - '@doctrine.annotation_reader'
      - '@Bundles\ApiBundle\Fetcher\EndpointFetcher'

  Bundles\ApiBundle\Fetcher\EndpointFetcher:
    - '@Bundles\ApiBundle\Fetcher\RolesFetcher'
    - '@Bundles\ApiBundle\Fetcher\FacadeFetcher'
    - '@Bundles\ApiBundle\Fetcher\DocblockFetcher'
    - '@doctrine.annotation_reader'

  Bundles\ApiBundle\Fetcher\FacadeFetcher:
    - '@Bundles\ApiBundle\Fetcher\DocblockFetcher'
    - '@Bundles\ApiBundle\Fetcher\StatusCodeFetcher'
    - '@Bundles\ApiBundle\Fetcher\PropertyCollectionFetcher'
    - '@doctrine.annotation_reader'
    - '@serializer'

  Bundles\ApiBundle\Fetcher\PropertyCollectionFetcher:
    - '@Bundles\ApiBundle\Fetcher\PropertyFetcher'
    - '@property_info'

  Bundles\ApiBundle\Fetcher\PropertyFetcher:
    - '@Bundles\ApiBundle\Fetcher\DocblockFetcher'
    - '@property_info'

  Bundles\ApiBundle\Fetcher\RolesFetcher:
    - '@security.access_map'
    - '@doctrine.annotation_reader'

  Bundles\ApiBundle\Fetcher\StatusCodeFetcher:
    arguments:
      - '@doctrine.annotation_reader'

  doctrine.annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader
