services:

  Bundles\ApiBundle\Listener\ViewListener:
    arguments:
      - '@serializer'
      - '@Bundles\ApiBundle\Fetcher\StatusCodeFetcher'
    tags:
      - { name: kernel.event_listener, event: kernel.view }

  Bundles\ApiBundle\Listener\ExceptionListener:
    arguments:
      - '@serializer'
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
