services:

  Bundles\ApiBundle\Listener\ViewListener:
    arguments:
      - '@serializer'
      - '@Bundles\ApiBundle\Parser\StatusCodeParser'
    tags:
      - { name: kernel.event_listener, event: kernel.view }

  Bundles\ApiBundle\Listener\ExceptionListener:
    arguments:
      - '@serializer'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
