services:

  Bundles\ApiBundle\Manager\TokenManager:
    arguments:
      - '@Bundles\ApiBundle\Repository\TokenRepository'
      - '@security.helper'

  Bundles\ApiBundle\Manager\WebhookManager:
    arguments:
      - '@Bundles\ApiBundle\Repository\WebhookRepository'

