services:

  Bundles\ApiBundle\Repository\TokenRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
    tags:
      - 'doctrine.repository_service'

  Bundles\ApiBundle\Repository\WebhookRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
    tags:
      - 'doctrine.repository_service'
