parameters:
  communication.processor: 'App\Communication\Processor\ExecProcessor'

services:
  App\Provider\SMS\SMSProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeSmsProvider'
    arguments: [ '@doctrine' ]
    public: true

  App\Provider\Call\CallProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeCallProvider'
    arguments:
      - '@App\Manager\MessageManager'
      - '@Bundles\TwilioBundle\Manager\TwilioCallManager'
      - '@Bundles\SandboxBundle\Manager\FakeCallManager'
      - '@event_dispatcher'
    public: true

  App\Provider\Email\EmailProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeEmailProvider'
    arguments: [ '@doctrine' ]
    public: true

  App\Provider\Storage\StorageProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeStorageProvider'
    arguments: [ '@kernel', '@router' ]
    public: true

  App\Provider\Minutis\MinutisProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeMinutisProvider'
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeOperationManager'
      - '@Bundles\SandboxBundle\Manager\FakeOperationResourceManager'
      - '@App\Manager\VolunteerManager'
    public: true
